print("Welcome to the Tip calculator!")
total_bill = input("What was the total bill? $")
total_bill_float = float(total_bill)
percentage_tip = input("What percentage tip would you like to give? 10, 12, or 15?\n")
percentage_tip_float = float(percentage_tip)
bill_split = input("How many people to split the bill?\n")
bill_split_int = int(bill_split)
expected_payment = ((percentage_tip_float / 100 * total_bill_float + total_bill_float) / bill_split_int)
print(f"Each person should pay {expected_payment}")
